/**
 * Generates docs/TEST_CASES.md from the test files, so the human-readable test-case matrix can never
 * drift from the tests that actually run. Every test title starts with an ID such as "AUTH-07".
 *   npm run docs:tests
 */
const fs = require('node:fs');
const path = require('node:path');

const root = path.join(__dirname, '..');
const testsDir = path.join(root, 'tests');

const AREAS = [
  ['AUTH', 'Authentication & sessions'],
  ['DOC', 'Documents: upload, read, search, edit'],
  ['VER', 'Versions & downloads'],
  ['SHR', 'Sharing, permissions & public links'],
  ['TRS', 'Trash, restore & permanent delete'],
  ['LIM', 'Limits & quotas'],
  ['ADM', 'Administration & bootstrap'],
  ['SYS', 'System: health, errors, security headers, rate limiting, docs, DB connection reuse'],
  ['CRON', 'Cron / scheduler endpoint (serverless deployments)'],
  ['UT-FT', 'Unit: file-type allow-list & content sniffing'],
  ['UT-VAL', 'Unit: request validation'],
  ['UT-PRM', 'Unit: permission model & serialisation'],
  ['UT-UTL', 'Unit: utilities'],
];

function walk(dir) {
  return fs.readdirSync(dir, { withFileTypes: true }).flatMap((e) => {
    const p = path.join(dir, e.name);
    return e.isDirectory() ? walk(p) : p.endsWith('.test.js') ? [p] : [];
  });
}

// it('ID title') and it.each(...)('ID title'); titles may contain escaped quotes.
const TEST_RE = /\bit(?:\.each\([\s\S]*?\))?\(\s*'([A-Z]+(?:-[A-Z]+)?-\d+) ((?:\\.|[^'\\])*)'/g;

const cases = [];
for (const file of walk(testsDir).sort()) {
  const src = fs.readFileSync(file, 'utf8');
  for (const m of src.matchAll(TEST_RE)) {
    cases.push({ id: m[1], title: m[2].replace(/\\'/g, "'").replace(/%s/g, '…'), file: path.relative(root, file) });
  }
}

// it.each expands one entry into several runs but is documented once.
const unique = cases.filter((c, i) => cases.findIndex((o) => o.id === c.id && o.title === c.title) === i);

const areaOf = (id) => AREAS.find(([prefix]) => id.startsWith(`${prefix}-`)) || ['?', 'Other'];
const natural = (a, b) => a.id.localeCompare(b.id, undefined, { numeric: true });

const lines = [
  '# Test-case matrix',
  '',
  '> Generated by `npm run docs:tests` from the test files — do not edit by hand. Every test title starts with its ID.',
  '',
  `**${unique.length} documented test cases** (some expand into several runs; \`npm test\` reports the total run count).`,
  '',
  '| Area | Cases |',
  '| --- | ---: |',
  ...AREAS.map(([prefix, name]) => `| ${name} | ${unique.filter((c) => areaOf(c.id)[0] === prefix).length} |`),
  '',
];

for (const [prefix, name] of AREAS) {
  const rows = unique.filter((c) => areaOf(c.id)[0] === prefix).sort(natural);
  if (!rows.length) continue;
  lines.push(`## ${name}`, '', '| ID | Behaviour verified | File |', '| --- | --- | --- |');
  for (const r of rows) lines.push(`| \`${r.id}\` | ${r.title.replace(/\|/g, '\\|')} | \`${r.file}\` |`);
  lines.push('');
}

fs.mkdirSync(path.join(root, 'docs'), { recursive: true });
fs.writeFileSync(path.join(root, 'docs', 'TEST_CASES.md'), lines.join('\n'));
console.log(`docs/TEST_CASES.md written (${unique.length} cases)`);
